"""initail migration

Revision ID: 363ee1aabc4b
Revises: 
Create Date: 2026-03-31 20:41:54.514301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363ee1aabc4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('university', sa.String(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('credit_units', sa.Integer(), nullable=False),
    sa.Column('grade_point', sa.Float(), nullable=True),
    sa.Column('target_grade_point', sa.Float(), nullable=True),
    sa.Column('ca_score', sa.Float(), nullable=True),
    sa.Column('ca_max_score', sa.Float(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    op.drop_table('users')
    # ### end Alembic commands ###
