"""Add course model

Revision ID: 47902c9d2fb7
Revises: 7a7543cdba13
Create Date: 2026-03-20 22:34:19.346239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47902c9d2fb7'
down_revision = '7a7543cdba13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('credit_units', sa.Integer(), nullable=False),
    sa.Column('grade_points', sa.Float(), nullable=True),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    # ### end Alembic commands ###
