"""rename grade points to grade_point

Revision ID: 590ffc143d7a
Revises: 47902c9d2fb7
Create Date: 2026-03-23 21:02:42.146053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590ffc143d7a'
down_revision = '47902c9d2fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_point', sa.Float(), nullable=True))
        batch_op.drop_column('grade_points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_points', sa.FLOAT(), nullable=True))
        batch_op.drop_column('grade_point')

    # ### end Alembic commands ###
