"""Add predictor fields to course model

Revision ID: c20c983c5ae7
Revises: a183283b6233
Create Date: 2026-03-29 22:38:06.188556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20c983c5ae7'
down_revision = 'a183283b6233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_grade_point', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ca_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ca_max_score', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('ca_max_score')
        batch_op.drop_column('ca_score')
        batch_op.drop_column('target_grade_point')

    # ### end Alembic commands ###
