"""add university and level to user

Revision ID: dd64409c47cc
Revises: 590ffc143d7a
Create Date: 2026-03-25 22:17:59.296437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd64409c47cc'
down_revision = '590ffc143d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('current_level', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('current_level')
        batch_op.drop_column('university')

    # ### end Alembic commands ###
